### ISSUE TITLE
See black after try to view a picture

### ISSUE THREAD

**Issue by heubergen** [rogora/hangish#3]
I can see picture in the chat-window, but if I click on one to see it (large)r I have to wait some seconds and then I just see a black picture.

See this picture for more:

![20150130130959](https://cloud.githubusercontent.com/assets/5529410/5975546/392545e6-a882-11e4-8fae-1ebc28a00630.jpg)

**Comment by rogora** [comment]
Does it happen only with this picture?
Can you open the same image on other clients?
What kind of picture is it? E.g. is it a GIF?

**Comment by heubergen** [comment]
Bug happen with every picture that I try (5 or more)
The image was send from a computer client and I can see it on my computer.

Okay I have tried a lot and here are the results:
It is sender/receiver independent.
Its happen on png and jpg file (other type not tested).
Its happen only by "big" pictures. (More than 1MB I guess)

I could give you my hangout address so we could find it out better.

**Comment by rogora** [comment]
I have just tested with a 3mb PNG picture and it works well; furthermore hangish is not directly responsible for image download, so, once it produces the right download link, it's finished.

You are the only one reporting this problem, and if you confirm that it is caused by big pictures, I'd say there is some problem with your phone or maybe network configuration.

**Comment by heubergen** [comment]
Hmm, okay. Is it possible that we chat on hangout so you can test it with exactly that picture that doesn't work for me?

You can find my G+ page here:
https://plus.google.com/+PatrickAlbrecht1

Just write me on and I send you the picture.

**Comment by rogora** [comment]
Hi, sorry for the long delay, but I've finally had the chance to reproduce your case.
The problem seems not to be with hangish, but somewhere in sailfish.
Indeed if you watch the logs when that happens you see: "Error after glEGLImageTargetTexture2DOES 501".

I think I should ask some Jolla guy about this. Did you gather any new info that may help in the meantime?

**Comment by heubergen** [comment]
No, I personally doesn't use the app very often in the last weeks.
But also no, I don't discovered any helpful information.
