### ISSUE TITLE
Cannot save more than one image from messages on a given day.

### ISSUE THREAD

**Issue by stephgosling** [rogora/hangish#39]
In some cases (perhaps not all?) I can only successfully download the first image I attempt to from a chat conversation I think because Hangish is saving images in the format YYYY-MM-DD and is silently failing when an image of that name already exists. 

Version affected: 0.8.2 (as available from the store)
Steps to reproduce:
- Receive a message with an image embedded (in my case from an Android user using the official Hangouts app, and the image is a JPG taken with her phone camera).
- Long-press to activate Pulley, select download image
- Hangish downloads image to ~/Pictures (curiously without file extension)
- Receive a second message with another image embedded
- Long-press to activate Pulley, select download image
- Hangish displays 'saved image' notification but does not save image.

If you mv the first image out of the way the download will succeed (and then tracker gets upset but that's not your problem ;)  )

**Comment by rogora** [comment]
This is interesting. Hangish uses the id that Google gives to the image, parsed from the url. So the name of the file should not be the problem.

About your curiosity:
the name is saved without the extension because the image can be have different formats, but the format cannot be parsed from the url. So, the easy hack to make sailfish always display the image correctly, was to remove the extension from the filename.

**Comment by stephgosling** [comment]
Yes I saw the extension stripping in the source comments so that does make sense (and tracker picks them up regardless). Regarding the saving issue I'd be curious to see if you are able to reproduce (we may all need to send pictures of kittens to each other or something ;) )
